sudo: required
language: cpp
services:
  - docker
env:
  #- TEST_CMSSW_VERSION=CMSSW_5_3_29 SCRAM_ARCH=slc6_amd64_gcc472 CHECKOUTSCRIPT=checkoutCmssw76xPackagesForSkimming.py
  - TEST_CMSSW_VERSION=CMSSW_7_6_3 SCRAM_ARCH=slc6_amd64_gcc493 CHECKOUTSCRIPT=checkoutCmssw76xPackagesForSkimming.py
  #- TEST_CMSSW_VERSION=CMSSW_8_0_26_patch1 SCRAM_ARCH=slc6_amd64_gcc530 CHECKOUTSCRIPT=checkoutCmssw80xPackagesForSkimming.py
compiler:
  - gcc
before_install:
  - docker pull claria/cvmfs-cms
before_script:
  - echo $HOME
  - sudo curl -o $HOME/short_rootfiles.tar https://cernbox.cern.ch/index.php/s/WeawecKp2BD2BH2/download
  - echo $HOME
  - sudo tar -xvf $HOME/short_rootfiles.tar -C /home/
  - ls /home/short
script:
  - docker run --privileged -e TEST_CMSSW_VERSION=${TEST_CMSSW_VERSION}
                            -e SCRAM_ARCH=${SCRAM_ARCH}
                            -e CHECKOUTSCRIPT=${CHECKOUTSCRIPT}
                            -v ${TRAVIS_BUILD_DIR}:/home/travis claria/cvmfs-cms /bin/bash 
                            -c "cd /home/; /home/travis/test_build.sh"
