sudo: required
language: cpp
services:
  - docker
env:
  - TEST_CMSSW_VERSION: CMSSW_5_3_29
  - TEST_CMSSW_VERSION: CMSSW_7_2_5
  - TEST_CMSSW_VERSION: CMSSW_7_4_2
compiler:
  - gcc
before_install:
  - docker pull claria/cvmfs-cms
script:
  - docker run --privileged -e TEST_CMSSW_VERSION=${TEST_CMSSW_VERSION} -v ${TRAVIS_BUILD_DIR}:/home/travis claria/cvmfs-cms /bin/bash -c "cd /home/; /home/travis/test_build.sh"
