sudo: required
language: cpp
services:
  - docker
env:
  #- CHECKOUTSCRIPT=checkoutCmssw80xPackagesForSkimming.sh SKIMMING_SCRIPT=Kappa/Skimming/higgsTauTau/kSkimming_run2_cfg.py ADDITIONAL_OUTPUT=false
  - CHECKOUTSCRIPT=checkoutCmssw76xPackagesForSkimming.sh SKIMMING_SCRIPT=Kappa/Skimming/higgsTauTau/kSkimming_run2_cfg.py ADDITIONAL_OUTPUT=false
  #- CHECKOUTSCRIPT=checkoutCmssw76xPackagesForSkimming.sh SKIMMING_SCRIPT=Kappa/Skimming/higgsTauTau/kSkimming_run2_cfg.py ADDITIONAL_OUTPUT=false
  # skim_tutorial1_basic.py - checkoutDummy.sh and checkoutTauRefit.py are not available
  #- CHECKOUTSCRIPT=checkoutTauRefit.py SKIMMING_SCRIPT=Kappa/Skimming/examples/skim_tutorial1_basic.py ADDITIONAL_OUTPUT=false
  #- CHECKOUTSCRIPT=checkoutDummy.sh    SKIMMING_SCRIPT=Kappa/Skimming/examples/skim_tutorial1_basic.py ADDITIONAL_OUTPUT=false
  #- CHECKOUTSCRIPT=checkoutDummy.sh    SKIMMING_SCRIPT=Kappa/Skimming/examples/skim_tutorial1_basic.py ADDITIONAL_OUTPUT=false
  # skim_tutorial2_configured - checkoutDummy.sh and checkoutTauRefit.py are not available
  #- CHECKOUTSCRIPT=checkoutTauRefit.py SKIMMING_SCRIPT=Kappa/Skimming/examples/skim_tutorial2_configured.py ADDITIONAL_OUTPUT=false
  #- CHECKOUTSCRIPT=checkoutDummy.sh    SKIMMING_SCRIPT=Kappa/Skimming/examples/skim_tutorial2_configured.py ADDITIONAL_OUTPUT=false
  # skim_tutorial4_full.py - empty
  # skim_tutorial9_HEPMC.py - configuration loads a hepmc file and converts it to kappa skimmed file. does not run properly
  #
  # zjet/
  # skim_53_cfg.py - re-do path to checkout script
  #- CHECKOUTSCRIPT=zjet/checkout53.sh    SKIMMING_SCRIPT=Kappa/Skimming/zjet/skim_53_cfg.py ADDITIONAL_OUTPUT=false
  # skim_74_cfg.py - re-do path to checkout script
  #- CHECKOUTSCRIPT=zjet/checkout74.sh    SKIMMING_SCRIPT=Kappa/Skimming/zjet/skim_74_cfg.py ADDITIONAL_OUTPUT=false
  # skim_76_cfg.py - no checkoutTauRefit.sh
  #- CHECKOUTSCRIPT=checkoutTauRefit.sh    SKIMMING_SCRIPT=Kappa/Skimming/zjet/skim_76_cfg.py ADDITIONAL_OUTPUT=false  
compiler:
  - gcc
before_install:
  - docker pull claria/cvmfs-cms
before_script:
  - echo $HOME
  - sudo curl -o $HOME/short_rootfiles.tar https://cernbox.cern.ch/index.php/s/WeawecKp2BD2BH2/download
  - echo $HOME
  - sudo tar -xvf $HOME/short_rootfiles.tar -C /home/
  - sudo ls /home/short
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - docker run --privileged -e CHECKOUTSCRIPT=${CHECKOUTSCRIPT}
                            -e SKIMMING_SCRIPT=${SKIMMING_SCRIPT}
                            -e ADDITIONAL_OUTPUT=${ADDITIONAL_OUTPUT}
                            -v ${TRAVIS_BUILD_DIR}:/home/travis 
                            -v '/home/short:/home/short' claria/cvmfs-cms /bin/bash 
                            -c "cd /home/; /home/travis/test_build.sh"
