# travis config for Kappa
sudo: required
language: cpp
notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - ./.install_dependencies.sh
install: 
  - make -C DataFormats/test
